# Generated by Django 5.0.5 on 2024-05-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
    ]
