# Generated by Django 5.0.5 on 2024-05-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("acts", "0002_remove_act_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="act",
            options={"ordering": ["-created"]},
        ),
    ]
